### PR TITLE
Split DocsPortingTool into two separate tools

### PR DESCRIPTION
**Pull request by carlossanlop**
@jeffhandley @RussKie 

As discussed, I am splitting the code into two separate solutions, one for porting from intellisense to docs (`PortToDocs.exe`), and one for porting from docs to triple slash comments (`PortToTripleSlash.exe`).

The purpose is to make it easier to work on the `PortToTripleSlash` project and modify the Docs classes as needed, without breaking the `PortToDocs` functionality, which is already **stable**.

I made sure of the following:

- The main readme file now points to two separate ones, one for each new tool.
- The internal readmes are updated.
- Each tool has its own `install_as_tool.ps1` script. I tested them and they work.
- I updated all the dependencies and made sure the unit tests work and pass for both tools.

Pending:

- ~Need the CI to run to verify that the yml does not need to be modified and that the tests still get executed and finish successfully in PRs.~

### CODE REVIEW

**Comment by carlossanlop** [comment]
The solutions build locally, and I was able to fix one CI failure by making sure we restore, build and test each solution separately.

Unfortunately, I do not know how to consume .NET 7.0 in the CI: https://github.com/carlossanlop/DocsPortingTool/runs/5386440105?check_suite_focus=true

```
Error: /usr/share/dotnet/sdk/[6](https://github.com/carlossanlop/DocsPortingTool/runs/5386440105?check_suite_focus=true#step:4:6).0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET [7](https://github.com/carlossanlop/DocsPortingTool/runs/5386440105?check_suite_focus=true#step:4:7).0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/home/runner/work/DocsPortingTool/DocsPortingTool/PortToTripleSlash/src/src.csproj]
Error: /usr/share/dotnet/sdk/6.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/home/runner/work/DocsPortingTool/DocsPortingTool/PortToTripleSlash/PortToTripleSlash/PortToTripleSlash.csproj]
Error: /usr/share/dotnet/sdk/6.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/home/runner/work/DocsPortingTool/DocsPortingTool/PortToTripleSlash/tests/tests.csproj]
Error: Process completed with exit code 1.
```

**Comment by carlossanlop** [comment]
I updated the projects to consume net6.0 instead. There's a chance that the `PortToTripleSlash` tool will complain when using it against dotnet/runtime or dotnet/winforms, I don't recall if it was a requirement for the tool to also consume the same .NET SDK version.

But for now, the tests pass when running against net6.0, so I'd like us to start this code split with a clean slate.

**Comment by carlossanlop** [comment]
Ping @jeffhandley @RussKie - If there are no comments/suggestions, let me know and I'll merge this.

**Review by jeffhandley — APPROVED** [review]
I've scanned it but won't be able to review it thoroughly. For the `csproj` files, I recommend using names different from `src` and `tests`--perhaps `PortToDocs.Libraries`, `PortToDocs.Tests`, `PortToTripleSlash.Libraries`, and `PortToTripleSlash.Tests`?

**Comment by RussKie** [comment]
How about the following folder structure, similar to how .NET repos are structured, e.g.:
```
/docs
/src
    /PortToDocs
        /src
        /tests
    /PortToTripleSlash
        /src
        /tests
```

**Comment by carlossanlop** [comment]
> How about the following folder structure, similar to how .NET repos are structured, e.g.:
> 
> ```
> /docs
> /src
>     /PortToDocs
>         /src
>         /tests
>     /PortToTripleSlash
>         /src
>         /tests
> ```

I like your suggestion, @RussKie . But I don't know what the `/docs` folder would be for.

By the way, I closed all the open PRs except this one, since this PR is going to be a breaking change for all the other PRs.

**Comment by RussKie** [comment]
“docs” was an example of other top-level folders.
And I guess at some point we’d have some docs for the tools, won’t we? 😃

**Comment by carlossanlop** [comment]
> And I guess at some point we’d have some docs for the tools, won’t we?

Oh, "docs" as in markdown files. For some reason those didn't come to mind. Sure, I can move the two docs files in this PR in that folder.

**Comment by RussKie** [comment]
Could you please clarify the purpose of these two folders, and why these files can't live in respective src folder?
image

**Comment by carlossanlop** [comment]
PortToDocs and PortToTripleSlash are both the folders that contain the console app.

**Comment by carlossanlop** [comment]
The Properties folder should've probably been ignored in the .gitignore, let me check if that's something we should do.

**Comment by RussKie** [comment]
Can we have it like this?
```
\src
    \PortToDocs 
        \src
            \app
            \Docs
            \IntelliSenseXml
```

**Comment by carlossanlop** [comment]
There are some common files under src that apply to both Docs and IntellisenseXml.

**Comment by RussKie** [comment]
Apologies for being vague. I meant to move \src\PortToDocs\PortToDocs to \src\PortToDocs\src\app

**Comment by RussKie** [comment]
Apologies for being vague. I meant to move \src\PortToDocs\PortToDocs to \src\PortToDocs\src\app. So that:
1. all source is under respective \src folder, and
2. it's obvious what the entry point is for each project

And the csproj (and any other top level files) should live in the project's \src folder too.

**Comment by carlossanlop** [comment]
The problem with that tree structure is that currently, the 'app' has its own csproj, and 'src' has its own csproj as well.

Moving the app with a csproj under src, which as a csproj, would force to be explicit about the files to include on the csproj files.

We have them as separate projects so that we keep the 'app' as an `<OutputType>Exe</OutputType>` and the src as a `<OutputType>Library</OutputType>`. This differenciation helped me a lot with unit testing.

I see that your intention is to move _all_ source code, whether its the exe or the library code, inside src, correct? So what do you think about this structure instead?

src/
    app/
        app.csproj
    libraries/
        Docs/
        IntellisenseXml/
        libraries.csproj

**Comment by RussKie** [comment]
Right, we can iterate on it later. Thank you.

**Comment by RussKie** [comment]
I think I may have been confused, I though Docs and IntellisenseXml were own projects. 

> ```
> src/
>     app/
>         app.csproj
>     libraries/
>         Docs/
>         IntellisenseXml/
>         libraries.csproj
> ```

Your suggested structure look good 👍

**Comment by carlossanlop** [comment]
I can do it now. Do you agree with my suggestion?

**Comment by RussKie** [comment]
Yep :)

**Comment by carlossanlop** [comment]
Hahah I hate chatting on GitHub comments. I see you agree. I'll do it. 😄

**Comment by carlossanlop** [comment]
@RussKie does it look good now?

**Comment by RussKie** [comment]
Yep. :shipit:

**Pull request merged**
